all:
	gcc -I src/include -L src/lib src/app.c src/camera.c src/main.c src/scene.c src/texture.c src/utils.c src/eventhandler.c src/menu.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lobj -lopengl32 -lm -o cube.exe -Wall -Wextra -Wpedantic
